version: "2"
linters:
  default: "fast"
  disable:
    - noinlineerr
    - nonamedreturns
    - err113
    - wsl
    - wsl_v5
    - gocognit
    - cyclop
    - gocyclo
    - maintidx
    - lll
    - funlen
    - nlreturn
    - gochecknoinits
    - testpackage
    - godox
    - funcorder
    - inamedparam
    - mnd
  enable:
    - revive
  settings:
    dupl:
      threshold: 500
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    depguard:
      rules:
        main:
          list-mode: strict
          allow:
            - $gostd
            - github.com/tychoish/fun
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
          exclude: ["**/internal/*.go"]
          arguments:
            - "say-repetitive-instead-of-stutters"

            # the following option(s) are a non-goal for the codebase:
            # - "check-private-receivers"

            # the following options are NOT provided because the
            # codebase passes the check.

            # - "disable-stuttering-check"
            # - "disable-checks-on-constants"
            # - "disable-checks-on-types"
            # - "disable-checks-on-variables"

            # these options are disabled (or enabled) because they
            # don't currently pass but their state should be inverted
            # as the codebase becomes compliant.

            # - "check-public-interface"
            - "disable-checks-on-functions"
            - "disable-checks-on-methods"
run:
  timeout: 1m
  tests: true
  allow-parallel-runners: true
issues:
  # fix: true
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
output:
  path-mode: "abs"
  show-stats: false
  formats:
    text:
      print-issued-lines: false
