# More info on config here: https://golangci-lint.run/usage/configuration/
run:
  deadline: 5m
  issues-exit-code: 1
  allow-parallel-runners: true
  tests: true

output:
  sort-results: false
  print-issued-lines: false
  print-linter-name: true

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  fix: true

linters-settings:
  govet:
    shadow: true
  gci:
    custom-order: true
    skip-generated: true
    sections:
      - standard
      - default
      - Prefix(github.com/tychoish)
  stylecheck:
    checks: ["all", "-ST1023", "-ST1003", "-ST4023"]

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - exhaustive
    - copyloopvar
    - gci
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unused
