name: go lint
on:
  pull_request:
    branches:
      - main
      - next
      - v0.10.x
  push:
    branches:
      - main
      - next
      - v0.10.x

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.24'
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v7
        with:
          # Required: the version of golangci-lint is required and
          # must be specified with patch version: we always use the
          # latest patch version.
          version: v2.0.0
          args: --timeout 4m
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF
