name: go test
on:
  pull_request:
  push:
    paths:
      - "**.go"
    branches:
      - main
      - next

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            "!test/"
            go.mod
            go.sum
      - name: go test
        if: env.GIT_DIFF
        run: |
          go test -race -timeout=2m ./...
