name: go test
on:
  pull_request:
    paths:
      - "**.go"
    branches:
      - main
      - next
      - v0.10.x
  push:
    paths:
      - "**.go"
    branches:
      - main
      - next
      - v0.10.x

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23"
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: go test
        if: env.GIT_DIFF
        run: |
          go test -race -timeout=5m ./...
